title: AutoUI Open Data Initiative
description: We want to promote open and transparent research practices within the AutoUI community
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
