title: AutomotiveUI Open Data Initiative
description: We promote open and transparent research practices within the automotive UI community
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
is_project_page: true